- name: nginx install and run
  hosts: web
  become: yes   #take sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package:  #heterongenous module that can work for all distors
    name: nginx
    state: present

  - name: run nginx
    ansible.builtin.package:
    name: nginx
    state: started
    enabled: yes