- name: variables from prompt
  hosts: web
  vars_prompt:  
  - name: COURSE
    prompt: Please enter the course name
  - name: TRAINER
    prompt: Pelase enter the Trainer name
  - name: DURATION
    prompt: Please enter the duration
  tasks:
  - name: print the course information
    ansible.builtin.debug:
    msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"