- name: variables from prompt
  hosts: web
  vars_prompt:  
  - name: COURSE
    prompt: Please enter the course name
    private: false # if not confidential
  - name: TRAINER
    prompt: Pelase enter the Trainer name
    private: false  # if not confidential
  - name: DURATION
    prompt: Please enter the duration
    private: false  # if not confidential
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"