- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with aws from PLAY level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false
  tasks:
  - name: print the information
    vars:
      # COURSE: "DevOps with AWS from TASK level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"

# Ansible can execute in the below sequence order
#1. Command line/args
#2. Task level
#